package com.agroo.agroo.model.enums;

public enum ActivityType {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGOUT,
    USER_UPDATED,
    USER_DELETED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_VERIFIED,
    POST_CREATED,
    POST_DELETED,
    COMMENT_CREATED,
    COMMENT_DELETED,
    GROUP_CREATED,
    GROUP_DELETED,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    PRICE_UPDATED,
    ALERT_CREATED,
    ALERT_DELETED,
    ADMIN_ACTION
}